language: ruby
before_install:
  # https://github.com/travis-ci/travis-rubies/issues/57#issuecomment-458981237
  - "find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete"
  - gem install bundler --version 2.2.10
notifications:
  email: false
  hipchat:
    rooms:
      secure: Mk3yGyQ/CYLsximKPCXKjzFf06i5T5rQsLtFI2XVBPhRPK4uy7ixFKHsKhS0ZYSP0htnbkvDvrCsTCECayvIXoP9YxvWWZXNy8/fATPlS1zA2jhdITzK+ol/8OCxc/vSpwm9EchMQVO3AE4wfbNdzAWMCJp5Y1GAqP9djzq7tjEoaUVZSGrDPHH/zk75vMFVYm5VHoqSMQVwXU4dh3YKiv0rogodXrNdlqCeYVH2lZUKe5QX5gu6G4oOyY0kYTpmD/6ENnGICVj12gMP12+xCEl/4447Fxk02bDA5DhBrKTMCgjEZSV0ImXZsH6pbwlU/v4zau251TPkGb0AlvfcbEqB+kEwgN56Rh9w8rGv8q9Qt3sX6btf1iCBcJUNJ4wuH82ZdgwbxYOxh0GLmws+t7mllf/chHoL7VF4ABQV0278psKnKGAZgIkR4mYcRXS4o3uG2/vKxS8nnFDn3Lo5RXie6pvIYvOC02pM83DzRvsyb+LygtwG+KqYHeTvt8i5pfArqL2nww4Klbng9t/OkZ0eliiXo1dcvyqoyIy7LuxRr7kTl4Dqo+L19e4+VUMarTeUJb3j+BThI4l+Rvk0N/smgDPk+0fwphG5wsnMEqoK346ZW6S9M54uHRaAkbPS7abrZXLLD0njASKfAbgIQG0/xJV09HNu4+oGVfv7Aik=
    template:
    - 'Gem - %{repository} #%{build_number} (%{build_url}) by %{author}: %{message}'
rvm:
- 2.4.0
deploy:
  provider: rubygems
  api_key:
    secure: JqaLIYBqJe7v3HOPxrtlGFf+2+crDHQ4CgpCeWJOGKbdwmg13spz7eEsVaH06IQ30cEbvxIw8mKigBK+oMMRaSlXQIHAowVOHAPTtJ7OItRb2Yvuh4MshV4MScnPHfoxs++6fnY0RF9JKovlss6Ybs6fRMZE1c+/pOl1h5lZ6oX+8VjC3DYGHHpk8ToKogQkipZsdY9uvamvFrgirNQGXEZb831xFpUgRWTWASgBVHcGMUI9Hj3g0gh6S8eULf86aB3/F36XrjkEM8l4W8W3Ux8ERg2q1DZtg7X5s8MvaG2AhGLdrTrAtJ6UILDSQAps7qppzHU3LM5rHMV/8rscsCDUCHbLkODsHVvT2nnBhBDQBpnKJ/FxbEQYckLdF4yhia97uE+69PoR4sZ8aTLD31cfo2FuCBO0STISuzxv03+t/AXC1ntFuVlHLxdZZm3NeJPXNUxowD1N3E/P3jtc9Q/RffKIw0oTbhHyzvkYUhhU0r8Eztu/sjMW23rzcLACWZa+Hv2FDRzWCcSgK1Ad6duxo5XBhLN6glaQ0w6YqNZ0xva3jMq2ILoiSQFeu5x/H9X6Xmt+KpF06gJ59kGXBJfESxxCeT6HA8ovD9xXUN8ENbNGk8nvoqh2anTHvYPvoMoDbtOztmqhUeyOLzB1ou4Y4SsLB6vBdd378uEjSgw=
  gem: atlassian_plugin_installer
  on:
    tags: true
    repo: Adaptavist/atlassian_plugin_installer
